Data structure
zetraxus/Kakuro pull request #2
Opened 2018-12-06 22:50 UTC by zetraxus

2018-12-06 23:55 UTC, PROZ-283766 commented on src/data_structure/board.java
> +    private field2D[][] gameMap;
```suggestion
    private field2D[][] gameBoard;
```

2018-12-06 23:55 UTC, PROZ-283766 commented on src/data_structure/board.java
> +    public board(byte width, byte height, field2D[] startMap) {
```suggestion
    public board(byte width, byte height, field2D[] startBoard) {
```

2018-12-06 23:55 UTC, PROZ-283766 commented on src/data_structure/board.java
> +        gameMap = new field2D[width][height];
```suggestion
        gameBoard = new field2D[width][height];
```

2018-12-06 23:55 UTC, PROZ-283766 commented on src/data_structure/board.java
> +                gameMap[j][i] = startMap[i * width + j];
```suggestion
                gameBoard[j][i] = startBoard[i * width + j];
```

2018-12-06 23:55 UTC, PROZ-283766 commented on src/data_structure/board.java
> +                if (gameMap[j][i].getType() == field2D.Type.INFOCOLUMN || gameMap[j][i].getType() == field2D.Type.INFOCOLUMNANDROW)
```suggestion
                if (gameBoard[j][i].getType() == field2D.Type.INFOCOLUMN || gameBoard[j][i].getType() == field2D.Type.INFOCOLUMNANDROW)
```

2018-12-06 23:55 UTC, PROZ-283766 commented on src/data_structure/board.java
> +                    columnsInfo.add(gameMap[j][i].getColumn());
```suggestion
                    columnsInfo.add(gameBoard[j][i].getColumn());
```

2018-12-06 23:55 UTC, PROZ-283766 commented on src/data_structure/board.java
> +                if (gameMap[j][i].getType() == field2D.Type.INFOROW || gameMap[j][i].getType() == field2D.Type.INFOCOLUMNANDROW)
```suggestion
                if (gameBoard[j][i].getType() == field2D.Type.INFOROW || gameBoard[j][i].getType() == field2D.Type.INFOCOLUMNANDROW)
```

2018-12-06 23:55 UTC, PROZ-283766 commented on src/data_structure/board.java
> +                    columnsInfo.add(gameMap[j][i].getRow());
```suggestion
                    columnsInfo.add(gameBoard[j][i].getRow());
```

2018-12-06 23:55 UTC, PROZ-283766 commented on src/data_structure/board.java
> +                gameMap[x][y].getWritable().setColumnFieldInfo(columnsInfo.elementAt(i));
```suggestion
                gameBoard[x][y].getWritable().setColumnFieldInfo(columnsInfo.elementAt(i));
```

2018-12-06 23:55 UTC, PROZ-283766 commented on src/data_structure/board.java
> +                columnsInfo.elementAt(i).addWritableFields(gameMap[x][y].getWritable());
```suggestion
                columnsInfo.elementAt(i).addWritableFields(gameBoard[x][y].getWritable());
```

2018-12-06 23:55 UTC, PROZ-283766 commented on src/data_structure/board.java
> +                gameMap[x][y].getWritable().setRowFieldInfo(rowsInfo.elementAt(i));
```suggestion
                gameBoard[x][y].getWritable().setRowFieldInfo(rowsInfo.elementAt(i));
```

2018-12-06 23:55 UTC, PROZ-283766 commented on src/data_structure/board.java
> +                rowsInfo.elementAt(i).addWritableFields(gameMap[x][y].getWritable());
```suggestion
                rowsInfo.elementAt(i).addWritableFields(gameBoard[x][y].getWritable());
```

2018-12-07 15:43 UTC, kam193 requested changes

2018-12-07 15:43 UTC, kam193 commented on src/data_structure/board.java
> +    public board(byte width, byte height, field2D[] startMap) {
Why `startMap` is only 1D array? I think 2D array should be better and simpler to use.

2018-12-07 15:43 UTC, kam193 commented on src/data_structure/board.java
> +    private field2D[][] gameMap;
I agree, rename `Map` to `Board`

2018-12-07 15:43 UTC, kam193 commented on src/data_structure/field2D.java
> +    public fieldInfo getColumn() {
I think, we need a constructor, setter or default values to can fill this fields.

2018-12-07 15:43 UTC, kam193 commented on src/data_structure/fieldInfo.java
> +    private Direction direction;
I think we don't need direction now.

2018-12-07 15:43 UTC, kam193 commented on src/data_structure/fieldInfo.java
> +    private byte fieldCount; // count of fields which should sum to variable sum in this class
Again: we need a constructor or setters to can fill this fields.

2018-12-07 15:43 UTC, kam193 commented on src/data_structure/fieldInfo.java
> +    public void addWritableFields(fieldWritable fieldWritable) {
Please add also a getter to can get connected fields

2018-12-07 15:43 UTC, kam193 commented on src/data_structure/fieldWritable.java
> +    private State state;
Please add setters/getters/another method to manipulate for fields.

2018-12-07 20:15 UTC, kam193 approved these changes

2018-12-07 20:38 UTC, merged